FROM node:22 AS frontend-build

WORKDIR /frontend

COPY frontend/package*.json ./
RUN npm install

COPY frontend/. .
RUN npm run build

FROM node:22 AS backend-build

WORKDIR /backend

COPY backend/package*.json ./
RUN npm install

COPY backend/. .
RUN npm run build

FROM node:22

WORKDIR /app

COPY backend/package*.json ./
RUN npm install --omit=dev

COPY --from=backend-build /backend/dist ./dist
COPY --from=frontend-build /frontend/dist/frontend/browser ./public

EXPOSE 3000

CMD ["node", "dist/main"]
